const Theme = [
    "--primary-color",
    "--primary-10-color",
    "--secondary-color",
    "--secondary-10-color",
    "--secondary-20-color",
    "--title-color",
    "--navbar-bg-color",
    "--menu-bg-color",
    "--menu-overlay-color",
    "--splash-bg-color",
    // Message colors =>
    "--message-reply-progress-active-color",
    "--message-reply-progress-idle-color",
    "--message-receive-bg-color",
    "--message-send-bg-color",
    "--message-text-color",
    "--message-username-color",
    "--message-date-color",
    "--message-input-text-color",
    "--message-input-button-color",
    "--message-input-button-icon-color",
    "--message-input-button-icon-disable-color",
    "--message-input-button-hover-color",
    "--message-down-button-color",
    "--message-down-button-hover-color",
    "--message-down-button-icon-color",
    "--message-input-placeholder-color",
    "--message-input-bg-color",
    "--message-reply-close-color",
    "--message-send-reply-bg-color",
    "--message-receive-reply-bg-color",
    "--message-reply-bg-color",
    // Room colors =>
    "--room-bg-color",
    "--room-name-color",
    "--room-last-msg-writer",
    "--room-last-msg-color",
    "--room-last-msg-date-color",
    // Form colors =>
    "--form-input-idle-bg-color",
    "--form-input-hover-bg-color",
    "--form-input-placeholder-color",
    "--form-input-text-color",
    "--form-input-error-color",
    "--form-button-text-color",
    "--form-button-hover-color",
    "--form-button-disabled-color",
    "--form-container-bg-color",
];

module.exports = Theme;